FROM golang:1.20 as build
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cloudrun ./cmd/server/main.go

FROM scratch
WORKDIR /app
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /app/cloudrun .
COPY --from=build /app/cmd/server/.env .
EXPOSE 8080
ENTRYPOINT ["./cloudrun"]